=== Oozeander/Jaxb_XMLSchema/target/classes/com/oozeander/xsd/personnes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
            jaxb:version="2.1">
    <xs:element name="personnes">
        <xs:complexType>
            <xs:group ref="personnes"/>
        </xs:complexType>
    </xs:element>

    <xs:group name="personnes">
        <xs:sequence>
            <xs:element ref="personne1"/>
            <xs:element ref="personne2"/>
            <xs:element ref="personne3"/>
            <xs:element ref="personne4"/>
            <xs:element ref="personne5"/>
            <xs:element ref="personne6"/>
            <xs:element ref="personne7"/>
            <xs:element ref="personne8"/>
        </xs:sequence>
    </xs:group>
    
    <xs:element name="personne1" type="personneAvecAttribut"/>
    <xs:element name="personne2" type="personneAvecAttributEtValeur"/>
    <xs:element name="personne3" type="personneComplexe"/>
    <xs:element name="personne4" type="personneListe1"/>
    <xs:element name="personne5" type="personneListe2"/>
    <xs:element name="personne6" type="personneChoice"/>
    <xs:element name="personne7" type="personneNoOrder"/>
    <xs:element name="personne8" type="personneRestriction"/>

    <xs:complexType name="personneAvecAttribut">
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="personneAvecAttributEtValeur">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="personneComplexe">
        <xs:sequence>
            <xs:element name="nom" type="xs:string" default="KETROUCI"/>
            <xs:element name="prenom" type="xs:string" fixed="Billel"/>
            <xs:element name="date" type="xs:date" nillable="true">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:class ref="java.util.Date"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <!--
         <xs:complexType name="liste">
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="skill" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>

         Pour Reutiliser (POJO Liste.java)
    -->

    <xs:complexType name="personneListe1">
        <xs:sequence>
            <xs:element name="nomComplet" type="xs:string"/>
            <xs:element name="skills">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="skill" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="list">
        <xs:list itemType="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="personneListe2">
        <xs:sequence>
            <xs:element name="nomComplet" type="xs:string"/>
            <xs:element name="skills" type="list"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nomEtPrenom">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personneChoice">
        <xs:sequence>
            <xs:choice>
                <xs:element name="nomComplet" type="xs:string"/>
                <xs:element name="nomEtPrenom" type="nomEtPrenom"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="personneNoOrder">
        <xs:all>
            <xs:element name="nomEtPrenom" type="nomEtPrenom"/>
            <xs:element name="date" type="xs:date">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:class ref="java.util.Date"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>
    
    <xs:simpleType name="restrictionAnneeEntreMinEtMax">
        <xs:restriction base="xs:gYear">
            <xs:maxInclusive value="2020"/>
            <xs:minInclusive value="1996"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="restrictionEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Developpeur"/>
            <xs:enumeration value="Architecte"/>
            <xs:enumeration value="Medecin"/>
            <xs:enumeration value="Pilote"/>
            <xs:enumeration value="President"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="personneRestriction">
        <xs:all>
            <xs:element name="initial">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][A-Z]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="anneeDeNaissance" type="restrictionAnneeEntreMinEtMax">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:class ref="java.math.BigInteger"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
            <xs:element name="profession" type="restrictionEnum"/>
            <xs:element name="motDePasse">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="8"/>
                        <xs:maxLength value="32"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:all>
        <xs:attribute name="id">
            <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                    <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== Oozeander/Jaxb_XMLSchema/src/main/resources/personnes.xml
<personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="com/oozeander/xsd/personnes.xsd">

    <personne1 value="billel"/>
    <personne2 id="1">Billel</personne2>
    <personne3 id="1">
        <nom>KETROUCI</nom>
        <prenom>Billel</prenom>
        <date>1996-09-09</date>
    </personne3>
    <personne4>
        <nomComplet>Billel KETROUCI</nomComplet>
        <skills>
            <skill>Java</skill>
            <skill>Hibernate</skill>
            <skill>JAXB</skill>
            <skill>Spring</skill>
            <skill>Angular</skill>
        </skills>
    </personne4>
    <personne5>
        <nomComplet>Billel KETROUCI</nomComplet>
        <skills>billel bakay meriem</skills>
    </personne5>
    <personne6>
        <nomComplet>Billel KETROUCI</nomComplet>
        <!--<nomEtPrenom>
            <nom>KETROUCI</nom>
            <prenom>Billel</prenom>
        </nomEtPrenom>-->
    </personne6>
    <personne7>
        <date>1996-09-09</date>
        <nomEtPrenom>
            <nom>KETROUCI</nom>
            <prenom>Billel</prenom>
        </nomEtPrenom>
    </personne7>
    <personne8>
        <initial>BK</initial>
        <anneeDeNaissance>1996</anneeDeNaissance>
        <profession>Developpeur</profession>
        <motDePasse>MonMotDePasse</motDePasse>
    </personne8>

</personnes>

=== Oozeander/Jaxb_XMLSchema/src/main/resources/personnes-generated.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="com/oozeander/xsd/personnes.xsd">
    <personne1 value="Billel"/>
    <personne2 id="1">Billel</personne2>
    <personne3 id="1">
        <nom>KETROUCI</nom>
        <prenom>Billel</prenom>
        <date xsi:nil="true"/>
    </personne3>
    <personne4>
        <nomComplet>Billel KETROUCI</nomComplet>
        <skills>
            <skill>Java</skill>
            <skill>Hibernate</skill>
            <skill>Spring</skill>
            <skill>Angular</skill>
        </skills>
    </personne4>
    <personne5>
        <nomComplet>Billel KETROUCI</nomComplet>
        <skills>Java Hibernate Spring Angular</skills>
    </personne5>
    <personne6>
        <nomComplet>Billel KETROUCI</nomComplet>
    </personne6>
    <personne7>
        <nomEtPrenom>
            <nom>KETROUCI</nom>
            <prenom>Billel</prenom>
        </nomEtPrenom>
        <date>2020-09-04+02:00</date>
    </personne7>
    <personne8 id="1170">
        <initial>BK</initial>
        <anneeDeNaissance>1996</anneeDeNaissance>
        <profession>Developpeur</profession>
        <motDePasse>monMotDePasse</motDePasse>
    </personne8>
</personnes>
